version: 2

models:
  - name: stg_tumores
    columns:
      - name: record_id
        data_tests:
          - unique
          - not_null
      - name: age
        data_tests:
          - not_null
      - name: gender
        data_tests:
          - accepted_values:
              arguments:
                values: ['male', 'female', 'other']
      - name: tumor_type
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['benign', 'malignant']