select
    row_number() over ()                                   as record_id,
    nullif(trim("Age"), '')::int                           as age,
    lower(nullif(trim("Gender"), ''))                      as gender,
    nullif(trim("Country"), '')                            as country,
    nullif(trim("Tumor_Size"), '')::numeric                as tumor_size,
    lower(nullif(trim("Tumor_Location"), ''))              as tumor_location,
    lower(nullif(trim("MRI_Findings"), ''))                as mri_findings,
    nullif(trim("Genetic_Risk"), '')::int                  as genetic_risk,
    {{ yes_no('"Smoking_History"') }}                      as smoking_history,
    {{ yes_no('"Alcohol_Consumption"') }}                  as alcohol_consumption,
    lower(nullif(trim("Radiation_Exposure"), ''))          as radiation_exposure,
    {{ yes_no('"Head_Injury_History"') }}                  as head_injury_history,
    {{ yes_no('"Chronic_Illness"') }}                      as chronic_illness,
    nullif(split_part("Blood_Pressure", '/', 1), '')::int  as systolic_bp,
    nullif(split_part("Blood_Pressure", '/', 2), '')::int  as diastolic_bp,
    {{ yes_no('"Diabetes"') }}                             as diabetes,
    lower(nullif(trim("Tumor_Type"), ''))                  as tumor_type,
    lower(nullif(trim("Treatment_Received"), ''))          as treatment_received,
    nullif(trim("Survival_Rate(%)"), '')::numeric          as survival_rate_pct,
    lower(nullif(trim("Tumor_Growth_Rate"), ''))           as tumor_growth_rate,
    {{ yes_no('"Family_History"') }}                       as family_history,
    lower(nullif(trim("Symptom_Severity"), ''))            as symptom_severity,
    {{ yes_no('"Brain_Tumor_Present"') }}                  as brain_tumor_present
from {{ source('raw', 'tumores') }}